# Generated by Django 4.2.5 on 2023-09-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpeg', upload_to='image/%Y', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
